### ISSUE TITLE
Req Fiture

### ISSUE THREAD

**Issue by hiyapo** [1mmunity/reqwstr#1]
Can You Scraping Web Example nekopoi.care or nhentai.net :)

**Comment by 1mmunity** [comment]
Sorry for the late reply, but you wanna scrape the what?!????

**Comment by 1mmunity** [comment]
Anyways, it depends if your ISP blocks it or not.

**Comment by hiyapo** [comment]
Can't You Scrape That? plz

**Comment by 1mmunity** [comment]
nah bro sry u down bad

**Comment by hiyapo** [comment]
https://vhtear.com/
I want To Scraper that for my API And My Bot

**Comment by hiyapo** [comment]
Like That

**Comment by 1mmunity** [comment]
Well technically this is a scraper, but it's a web application, you can't use/integrate it for your bot. If you want to integrate some scraping i suggest these libraries.

- [Puppeteer - Screenshot site](https://www.npmjs.com/package/puppeteer)
- [node-fetch - Raw HTML scraping](https://www.npmjs.com/package/node-fetch)

**Comment by hiyapo** [comment]
can't you make me a example

**Comment by hiyapo** [comment]
Are You Live In Indonesia And You Live In Makassar City?
